[tool.poetry]
name = "Thebot"
version = "0.1.0"
description = "chatbot creado n lenguaje phyton para @THECLUBServer"
authors = ["GMEK STUDIOS <EMALI.HERE>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.21.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
 
